In [1]:
import torch
import numpy as np

In [2]:
# rand 생성 
torch.rand(2, 2)

tensor([[0.9230, 0.6969],
        [0.8175, 0.3735]])

In [3]:
# 0 생성
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
# 1 생성
a = torch.ones(2, 2, dtype=torch.int)
a

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [6]:
# torch data type 확인 방법
a.dtype

torch.int32

In [7]:
a.size()

torch.Size([2, 2])

In [8]:
torch.tensor([2.5, 0.1])

tensor([2.5000, 0.1000])

In [10]:
b = torch.rand(2, 2)
b

tensor([[0.3714, 0.6200],
        [0.2813, 0.7865]])

In [11]:
c = torch.rand(2, 2)
c

tensor([[0.1332, 0.2744],
        [0.1719, 0.1973]])

In [12]:
# torch 덧셈 방법 1
d = b + c
d

tensor([[0.5045, 0.8945],
        [0.4533, 0.9838]])

In [13]:
# torch 덧셈 방법 2
torch.add(b, c)

tensor([[0.5045, 0.8945],
        [0.4533, 0.9838]])

In [14]:
c.add_(b)
c

tensor([[0.5045, 0.8945],
        [0.4533, 0.9838]])

In [16]:
# torch.add, sub, mul. div
d[:, 0] # all colums, first row

tensor([0.5045, 0.4533])

In [17]:
d[1, 1]

tensor(0.9838)

In [18]:
d[1, 1].item() # available only one

0.9838443398475647

In [20]:
x = torch.rand(4, 4)
x

tensor([[0.3570, 0.5932, 0.9541, 0.7980],
        [0.7879, 0.6983, 0.8181, 0.9289],
        [0.9588, 0.6439, 0.2394, 0.1031],
        [0.1761, 0.9584, 0.2517, 0.5194]])

In [22]:
y = x.view(-1, 8)
y

tensor([[0.3570, 0.5932, 0.9541, 0.7980, 0.7879, 0.6983, 0.8181, 0.9289],
        [0.9588, 0.6439, 0.2394, 0.1031, 0.1761, 0.9584, 0.2517, 0.5194]])

In [23]:
y.size()

torch.Size([2, 8])

In [24]:
hi = torch.ones(5)
hi

tensor([1., 1., 1., 1., 1.])

In [25]:
bye = hi.numpy()
bye

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
# hi, bye 는 같은 메모리를 공유하므로, 하나를 수정하게 되면 같이 변경된다.

hi.add_(1)
print(hi)
print(bye)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
sk = np.ones(5)
sk

array([1., 1., 1., 1., 1.])

In [28]:
kt = torch.from_numpy(sk)
kt

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [29]:
sk += 1
print(sk)
print(kt)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [31]:
alpha = torch.ones(5, requires_grad=True)
alpha

tensor([1., 1., 1., 1., 1.], requires_grad=True)